apiVersion: v1
kind: Config

clusters:
- name: minikube
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMk1ERXhOVEExTVRZek9Wb1hEVE0yTURFeE5EQTFNVFl6T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1MyClQydlVOa1RHQ3hkWEZWVnN0Q3FBQW0rNlJ6U0VNQituOEtXL1RqemhsdlZIYklMcHEwUUlkam5mL2h2S0V0QVEKR3U5aG42RDdiQ1ZGYXNxYTJYT1JqUVArQ0JHWk0wMk4zWkRBb3JKNWh2N0hkVnlpME5DU0E5KzQ1OXQxNmwwbQo2YjBRcXJlQ2YrdmloUDY0dkxvenpSN0p1bWRvSS94ZlZqa2hMWit2UytyUXBnRmlxbjM4emlOTlhsTkxmd0pKCjlwTitRMHQxTTVMUXJFelFSZnIvcnJWZkFTL2NMbStRS1pjZjFneHFnZmVUOTI2NWwrckZuQ3FEUGNlRlBJdmsKVldTUU1BdjdjVVNwd0lTaTg3azRBbHFCQ2l2ZEJ5OVYrQ2VMd3liRTNYUStFWW90bnFPR0JveGJOaFo5bHdFRwo3Nzh0Y3JwVUNUbGpPWWNuaXQ4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUTC9iWWNVZFN2cDdXOG80cUxWcThHWTBmUUpUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrQm0xSVhXRwpIRXp1eHF1WEFabHpXbURZTUNqQlBFenBabUV6OXF2UFdFVWROYTFjeU15TUhGQjRQNDdad1JvZktsTTdrdDN4ClpBSTgrbWYzTGdYM3kwenhRdGR3U2YrY2tyT3RPTnNDU2FEV2ZGZU80Y3YxTmxBMmtPZStGY2djUGpMYnVKTUsKZFkraFI2cFhiM1lqZ3d5eGxxTG5qcUdJclJhMU9uT0lyL3hYek1rY0sraXlvRjZvWDlUdkdKNWlHbXA1WkEyZwpvNmlNRG52VzMxWnZxZzdNMWhVNHVIZCtwVmoxT2ZaK0xENWdGTlZ6Z2RDUXRsUUNaSm5tVEF0dUhEL2tRSk9KCnNzSjljeVBXeFJkMWFmU0JhSmNsSFd0TlZDcWg5cElwZzJBS1JoQ0NqeUQvYVlMMG1lcTVxRzVzYU9nK1E3T0MKTksxOGdhM1NVb1B4amc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:62850

contexts:
- name: minikube
  context:
    cluster: minikube
    namespace: default
    user: jenkins-s

current-context: minikube

users:
- name: jenkins-s
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IncyeWxONVo1R1ZHa1FWc2oyUlh2OWQ4bGhIek5jSmNpdjAxaExydTd6NkUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY5MDAxODYyLCJpYXQiOjE3Njg5OTgyNjIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNTQzZTVjNjItODZjYy00Mzk1LTk2ODMtMDA2MjM3YTBmOTg2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtcyIsInVpZCI6Ijc3Mjc1NjdkLWRkMDAtNDg4NS04M2QwLTUwZDZhOTdhNzNiZiJ9fSwibmJmIjoxNzY4OTk4MjYyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpqZW5raW5zLXMifQ.ykmtdyb3i7DZTanxi4AyRwrZXhDH-arrA04FXYhbutRkwvNv2aAhvD-SIfarz3re7ZrKSWM1Rj4opYGNV6oTS-yPJRVdJnJpBRz93E6hANxKxg2oISGPX4QnKidl1X7B8HKy21OOZSXwbwAYzpelZB_2l3WBMA5njxWv3Tlb2y5bdERtQDiRC38U7oyUC9WGoNZerJz-ggCFr4shmvaOGmH2PK_DpyhuCsjydKbiLVWGcDC4VNnz51O1l7PQdEUsjcegxcnTgpA3XA5lfTJAvPYVZGhidA_X1i-4d9yqhllpOx0q7BaC6FbejuyJ8lsXaO3b6s4ThVUQWtB2Ktku3Q
